### ISSUE TITLE
Listar Categoria

### ISSUE THREAD

**Issue by MessiasOli** [tgspn/gestao-financeira-doo#3]
- [x] Criar uma tela de listagem de Categoria.
- [x] Criar botão de criar nova categoria.
- [x] Criar botão de editar
    - [x] Desabilitar o botão editar caso nenhuma categoria for selecionada.
- [x] Criar botão de apagar
    - [x] Desabilitar o botão apagar caso nenhuma categoria for selecionada.
    - [x] Perguntar se deseja realmente deseja apagar a categoria.
- [x] Criar um Controller de Categorias.
- [x] Criar um metodo para listagem dos Categorias.
- [ ] Criar Teste de listagem

**Comment by tgspn** [comment]
@MessiasOli , alguns forms estão abrindo em posições aleatórias, acredito ser interessante abrir todos os sub forms no centro do parente. 

Pra isso utilize a propriedade `StartPosition` com o valor `CenterParent`.

![image](https://user-images.githubusercontent.com/19411050/89239201-f0506000-d5ce-11ea-8977-85ca7a3536de.png)

**Comment by MessiasOli** [comment]
@tgspn Ótimo apontamento, preciso ajustar as fontes e alguns detalhes para melhorar o visual como um todo visando a padronição, se quiser criar um card para esse ajuste... aí ja pode por padronização das fontes para "Microsoft PhagsPa"
O que acha ?
Aí assim que sobrar um tempo eu ataco eles!
